/**
 * Type definitions for Axiom Core Web UI
 * This file contains all TypeScript interfaces to replace "any" types throughout the project
 */

// Import types from other modules for re-export
import type { AgentRole } from './marketplace';
import type { AgentMessage } from '../core/communication/AgentMessageBus';

// Define missing types to resolve barrel export issues
export type ViewMode = 'grid' | 'list' | 'card';
export type KitType = 'BASIC' | 'PREMIUM' | 'ENTERPRISE';
export interface Agent {
  id: string;
  name: string;
  role: string;
  status: 'ACTIVE' | 'INACTIVE' | 'PENDING';
}

// ============================================================================
// WEBSOCKET EVENT TYPES
// ============================================================================

/**
 * Represents the type of WebSocket event that can be emitted
 */
export type WebSocketEventType = 'DIAGNOSTIC' | 'MANDALA_UPDATE' | 'LLM_TOKEN';

/**
 * Represents a WebSocket event with its payload
 */
export interface WebSocketEvent {
  type: WebSocketEventType;
  payload: WebSocketEventPayload;
}

/**
 * Represents the payload for different WebSocket event types
 */
export interface WebSocketEventPayload {
  // DIAGNOSTIC event payload
  cpu?: number;
  memory?: number;
  
  // MANDALA_UPDATE event payload
  state?: 'EVOLVING' | 'IDLE';
  xp?: number;
  
  // LLM_TOKEN event payload
  token?: string;
}

// ============================================================================
// DREAM FACTORY TYPES
// ============================================================================

/**
 * Represents the state of the dream generation process
 */
export interface DreamState {
  seed: string;
  dreamLog: string[];
  structuredData: DreamInsight;
  artifacts: DreamArtifact[];
  feedback: string[];
  iterationCount: number;
  qualityScore: number;
}

/**
 * Represents an insight generated by the dream factory analyst agent
 */
export interface DreamInsight {
  concept: string;
  description: string;
  feasibility: 'HIGH' | 'MEDIUM' | 'LOW';
  novelty: number; // 1-10 scale
  utility: number; // 1-10 scale
  tags: string[];
  confidence: number; // 0-1 scale
}

/**
 * Represents an artifact created by the dream factory builder agent
 */
export interface DreamArtifact {
  id: string;
  type: 'CODE' | 'DATASET' | 'DOCUMENT' | 'SCHEMA';
  title: string;
  content: string;
  language?: string; // For code artifacts
  format?: string; // For dataset artifacts
  createdAt: number;
}

/**
 * Represents the evaluation result from the judge agent
 */
export interface DreamEvaluation {
  novelty_score: number; // 1-10
  feasibility_score: number; // 1-10
  utility_score: number; // 1-10
  final_score: number; // 1-10
  decision: 'APPROVE' | 'REJECT' | 'REFINE';
  feedback: string;
}

/**
 * Represents a log entry from the dream factory process
 */
export interface DreamLogEntry {
  agent: string;
  data: string | object;
  timestamp?: number;
}

// ============================================================================
// SWARM CONSENSUS TYPES
// ============================================================================

/**
 * Represents a proposal submitted to the swarm for consensus
 */
export interface Proposal {
  id: string;
  agentId: string;
  actionType: 'TRANSACTION' | 'DATA_UPDATE' | 'SECURITY_ALERT' | 'BUY' | 'SELL' | 'DEPLOY';
  payload: ProposalPayload;
  timestamp: number;
}

/**
 * Represents the payload for different proposal types
 */
export interface ProposalPayload {
  // TRANSACTION payload
  amount?: number;
  currency?: string;
  target?: string;
  
  // DATA_UPDATE payload
  dataKey?: string;
  dataValue?: string | number | boolean;
  
  // SECURITY_ALERT payload
  threatLevel?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  description?: string;
  
  // BUY/SELL payload
  asset?: string;
  price?: number;
  
  // DEPLOY payload
  environment?: 'DEVNET' | 'TESTNET' | 'MAINNET';
  contract?: string;
}

/**
 * Represents the result of a consensus decision
 */
export interface ConsensusResult {
  approved: boolean;
  score: number; // 0.0 to 1.0
  approvals: number;
  rejections: number;
  note: string;
  actionId?: string; // For backward compatibility with UI
  approvalRate?: number; // For backward compatibility
  participatingAgents?: number; // For backward compatibility
}

/**
 * Represents a node in the swarm topology
 */
export interface SwarmNode {
  id: string;
  group: number; // 1: Agent, 2: Hallucination, 3: Core
  val: number;   // Size
  x?: number;
  y?: number;
  z?: number;
}

/**
 * Represents a link between nodes in the swarm topology
 */
export interface SwarmLink {
  source: string;
  target: string;
  strength?: number;
}

/**
 * Represents the swarm graph data structure
 */
export interface SwarmGraphData {
  nodes: SwarmNode[];
  links: SwarmLink[];
}

// ============================================================================
// AGENT DATA STRUCTURES
// ============================================================================

/**
 * Represents an insight generated by an agent
 */
export interface AgentInsight {
  id: string;
  agentId: string;
  type: 'MARKET' | 'SECURITY' | 'PERFORMANCE' | 'STRATEGIC';
  title: string;
  description: string;
  confidence: number; // 0-1
  data: Record<string, unknown>;
  timestamp: number;
}

/**
 * Represents an action that can be performed by an agent
 */
export interface AgentAction {
  id: string;
  agentId: string;
  type: 'BUY' | 'SELL' | 'DEPLOY' | 'ANALYZE' | 'ALERT';
  title: string;
  description: string;
  payload: Record<string, unknown>;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  timestamp: number;
}

/**
 * Represents a task in the operations automation system
 */
export interface OperationTask {
  id: number | string;
  name: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  time: string;
  progress?: number; // 0-100
  error?: string;
}

/**
 * Represents a pending action requiring approval
 */
export interface PendingAction {
  type: string;
  payload: Record<string, unknown>;
  id: string;
  details: string;
}

// ============================================================================
// API ERROR TYPES
// ============================================================================

/**
 * Represents a standardized API error response
 */
export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
  timestamp: number;
  requestId?: string;
}

/**
 * Represents different types of API errors
 */
export type ApiErrorType = 
  | 'VALIDATION_ERROR'
  | 'AUTHENTICATION_ERROR'
  | 'AUTHORIZATION_ERROR'
  | 'NOT_FOUND'
  | 'RATE_LIMIT_EXCEEDED'
  | 'INTERNAL_SERVER_ERROR'
  | 'EXTERNAL_SERVICE_ERROR'
  | 'TIMEOUT_ERROR';

/**
 * Represents error details for specific error types
 */
export interface ApiErrorDetails {
  field?: string; // For validation errors
  service?: string; // For external service errors
  retryAfter?: number; // For rate limit errors
  stack?: string; // For internal errors (dev only)
}

// ============================================================================
// COMPONENT STATE AND PROPS TYPES
// ============================================================================

/**
 * Represents props for the ControlHub component
 */
export interface ControlHubProps {
  onSystemStart?: () => void;
  onSystemPause?: () => void;
  onSystemStop?: () => void;
  onSyncData?: () => void;
  systemStatus?: 'OPTIMAL' | 'WARNING' | 'CRITICAL';
}

/**
 * Represents props for the PolyphaseMonitor component
 */
export interface PolyphaseMonitorProps {
  initialLogs?: string[];
  refreshInterval?: number;
  maxLogEntries?: number;
}

/**
 * Represents props for the SwarmHologram component
 */
export interface SwarmHologramProps {
  initialData?: SwarmGraphData;
  onNodeClick?: (node: SwarmNode) => void;
  onLinkClick?: (link: SwarmLink) => void;
  showControls?: boolean;
  autoRotate?: boolean;
}

/**
 * Represents props for the SwarmConsensusVisualizer component
 */
export interface SwarmConsensusVisualizerProps {
  autoSimulate?: boolean;
  showDetails?: boolean;
  refreshInterval?: number;
}

/**
 * Represents props for the OperationsAutomationAgent component
 */
export interface OperationsAutomationAgentProps {
  initialTasks?: OperationTask[];
  autoApprove?: boolean;
  notificationThreshold?: 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

/**
 * Represents props for icon components
 */
export interface IconProps {
  size?: number;
  className?: string;
  color?: string;
}

/**
 * Represents props for control buttons
 */
export interface ControlButtonProps {
  icon: React.ComponentType<IconProps>;
  label: string;
  color: string;
  borderColor: string;
  onClick?: () => void;
  disabled?: boolean;
}

/**
 * Represents props for metric display boxes
 */
export interface MetricBoxProps {
  label: string;
  value: string;
  icon: React.ComponentType<IconProps>;
  color: string;
  trend?: 'UP' | 'DOWN' | 'STABLE';
}

// ============================================================================
// LOGGING AND AUTH TYPES
// ============================================================================

/**
 * Represents metadata for authentication events
 */
export interface AuthEventMetadata {
  ip?: string;
  userAgent?: string;
  sessionId?: string;
  location?: string;
  deviceId?: string;
}

/**
 * Represents the status of an authentication event
 */
export type AuthEventStatus = 'SUCCESS' | 'FAILURE';

// ============================================================================
// LATTICE AND TOPOLOGY TYPES
// ============================================================================

/**
 * Represents a node in a toric lattice structure
 */
export interface LatticeNode {
  id: string;
  x: number;
  y: number;
  connections: string[];
  data?: Record<string, unknown>;
}

/**
 * Represents a data point in the system
 */
export interface DataPoint {
  id: string;
  timestamp: number;
  value: number | string;
  source: string;
  metadata?: Record<string, unknown>;
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Represents a generic response wrapper for API calls
 */
export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: ApiError;
  timestamp: number;
}

/**
 * Represents pagination parameters
 */
export interface PaginationParams {
  page: number;
  limit: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

/**
 * Represents paginated response data
 */
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
  hasNext: boolean;
  hasPrev: boolean;
}

// Export all types for easy importing
export type {
  // Re-export existing types from other modules
  AgentRole,
  AgentMessage,
};